name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Ensure this matches your repository configuration
        settings-path: ${{ github.workspace }}

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4 # Use the latest stable version

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        TOKEN: ${{ secrets.JAVA_TOKEN }}
