name: Publish Package to GitHub Packages

on: push
   
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Updated distribution name

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }} # Use GitHub's default token

      - name: Clean up Gradle cache (optional)
        run: ./gradlew clean
        env:
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }} # Use GitHub's default token
